SearchAppGrpRoles="xpath://div[@class='search-filter--container']//input[@placeholder='Search']"
AddNewAppGrpRole="xpath://button/i[@class='fa fa-plus']"
AppGrpRoleName="id:name"
AppGrpRoleDesc="id:description"
GlobalRoleDropdown="xpath://div[contains(@class,'basic-single')]"
GlobalRoleDropdownValues="xpath://div[contains(text(),'index')]"
UsersSearch="xpath://div[@class='rdl-filter-container']/input[@data-key='available']"
MoveAllRightButton="xpath://div[@class='rdl-actions-right']/descendant::button[contains(@class, 'rdl-move-all')]"
SaveButton="xpath://button[contains(text(),'Save')]"
SearchedAppGrpRole="xpath://span[contains(text(),'index')]"
