SCELogo="xpath://span[contains(text(),'CDR - SCE')]"
New="xpath://*[@class='fa fa-caret-down']"
UserOptions="xpath://a[@class='dropdown-toggle']/i[@class='fa fa-user']"
Promote="xpath://a[@title='Promote Session User Role']"
Demote="xpath://a[@title='Demote Session User Role']"
Manage="xpath://a[@title='Manage']"
ManageOrgText="xpath://h2[text()='Manage Organization']"
Organization="xpath://a[@title='Organization']"
Steps="xpath://a[@title='Steps']"
AppGroups="xpath://a[@title='App Groups']"
AppGroupRoles="xpath://a[@title='App Group Roles']"