TasksButton = "id:deliverables-link"
NewTask = "xpath://a[@class='new-task-link']"
TaskNameInput = "id:deliverable_title"
WorkflowSelect = "xpath://span[contains(@id,'deliverable_workflow_id-container')]"
TasksSelectSearchTextInput = "xpath://span[contains(@class,'search--dropdown')]//input[@role='searchbox']"
TaskGroupSelect = "xpath://span[contains(@id,'deliverable_category_id-container')]"
QCGroupSelect = "id:deliverable_qc_group_id"
DueDateInput = "id:deliverable_due_date"
AnalysisPointsInput = "id:deliverable_complexity"
CreateButton = "xpath://button[text()='Create']"
TaskCreatedPrompt = "xpath://span[text()='Task created successfully.']"
ListedTask = "xpath://p[@class='task__text']"
ProgsPage = "xpath://a[contains(text(),'progs (0)')]"
ProgPathInput = "xpath:(//input[contains(@id,'file_path')])[1]"
OutputPathInput = "xpath:(//input[contains(@id,'file_path')])[2]"
SaveButton = "xpath://button[text()='Save']"
TrackUpdatedPrompt = "xpath://span[text()='Track files updated successfully.']"
CloseTaskButton = "xpath://div[@class='deliverable-model-header']//div[@class='modal__header__close']"
ProgAssignVerify = "xpath://span[@class='heading']//a[contains(text(),'file_copier.rb')]"
