Search = "xpath://input[@placeholder='Search']"
SearchResults = "xpath://a[@data-no-turbolink]"
Repository = "xpath://span[text()='Repository']"
UploadFile = "xpath://input[@id='user_file_attachment']"
SasProg = "xpath://a[text()='dm_sas7bdat_prog.sas']"
RubyProg = "xpath://a[text()='file_copier.rb']"
PythonProg = "xpath://a[text()='pythonSecureExecution.py']"
RProg = "xpath://a[text()='R.r']"
SasOutput = "xpath://a[text()='dm.sas7bdat']"
RubyROutput = "xpath://a[text()='output.txt']"
PythonOutput = "xpath://a[text()='output0.txt']"
FileThreeBars = "xpath://i[@class='fa fa-bars']"
SecondThreeBars = "xpath:(//i[@class='fa fa-bars'])[2]"
ThirdThreeBars = "xpath:(//i[@class='fa fa-bars'])[3]"
ThreeBarsRun = "xpath://a[@aria-label='Run']"
ThreeBarsUnzip = "xpath://a[@aria-label='Unzip']"
FileSearch = "xpath:(//input[@placeholder='Search'])[2]"
sas7bdat = "xpath://a[text()='raw_dm.sas7bdat']"
xpt = "xpath://a[text()='ae2.xpt']"
PreparingForViewing = "xpath://span[contains(text(),'Preparing for viewing')]"
StudyIDColumn = "xpath://th[contains(@class,'cell')]//span[text()='STUDYID']"
RowCheckSas = "xpath://tr[contains(@class,'table__row')]//td[text()='DM']"
RowCheckXpt = "xpath://tr[contains(@class,'table__row')]//td[text()='AE']"
ConvertCSVInline = "xpath://a[@class='unsupported-file--convert btn btn--primary']"
UnzipInitiatedPrompt = "xpath://span[text()='File extraction initiated.']"
UnzipFinishedPrompt = "xpath://span[text()='Zip Extraction Completed.']"
SelectFirstFile = "xpath://span[contains(@class,'file_select')]//input[@type='checkbox']"
AddToClipboardButton = "xpath://button[contains(@class,'add-to-clipboard')]"
AddedToClipboardPrompt = "xpath://span[text()='Successfully added to clipboard.']"
SelectAllClipboard = "xpath://input[@name='clip-checkbox-select']"
PasteHere = "xpath://button[@class='btn js-paste-clipboard-items']"
MoveHere = "xpath://button[@class='btn js-move-clipboard-items ']"
