NewWorkspace = "xpath://span[@class='add-workspace']//i[@class='fa fa-plus']"
WorkspaceNameInput = "id:study_name"
CreateWorkspace = "xpath://input[@name='commit']"
WorkspaceConfirmation = "xpath://span[contains(text(),'Your workspace creation request has been initiated.')]"
WorkspaceSearch = "xpath://input[@placeholder='Search for workspace']"
WorkspaceInList = "xpath://a[@title='index']"
Workspace1 = "xpath://span[@class='workspace-name']//a"
SelectForMerge = "xpath://select[@class='merge-workspace-select']"
SelectAll = "xpath://button[@class='select--all']"
MergeConfirm = "xpath://button[@class='btn btn--small merge-submit-btn']"
MergeSuccess = "xpath://p[contains(text(),'Merge completed successfully for all')]"
PullSuccess = "xpath://p[contains(text(),'Pull changes completed successfully for all')]"
CloseButton = "xpath://button[text()='Close']"
SasProgAlt = "xpath://a[text()='dm_sas7bdat_prog_nocomments.sas']"
DependenciesSuccess = "xpath://span[text()='Detected Dependencies successfully.']"
DependenciesCloseButton = "xpath://div[@class='modal__header__close']"
EditButtonInWorkspaceDashboard = "xpath://a[@id='editbtn']"
SaveButtonInWorkspaceDashboard = "xpath://a[@id='savebtn']"
TextInput = "xpath://textarea"
UpdateFileButton = "xpath://input[@name='commit']"
UpdatedFileVerify = "xpath://div[text()='test']"
