AccessButton = "id:access-link"
UserSearchDropdown = "xpath://span[@class='search-dropdown']"
UserSearchInput = "xpath://input[@name='search-string']"
FirstUserChoice = "xpath:(//div[@class='multi-select-checkbox__dropdown']//label)[1]"
UserSearchClose = "xpath://button[text()='Close']"
RoleSelect = "xpath:(//div[contains(@class,'select__value-container')])[1]"
RoleInput = "id:react-select-2-input"
AssignButton = "xpath://button[text()='Assign']"
AssignYes = "xpath://div[@class='action-text']//button[@title='Yes']"
AssignmentConfirm = "xpath://span[@class='info'][text()='Assignment initiated']"
