NewFolder="xpath://a[contains(@title,'Create a new folder')]"
RootFolders = "id:root-folders-link"
FolderNameInput = "id:folder_name"
FolderTypeButton = "id:select2-folder_folder_type_id-container"
FolderTypeSelect = "id:folder_folder_type_id"
PermissionTypeButton = "id:select2-folder_permission_type-container"
PermissionTypeSelect = "id:folder_permission_type"
CreateFolder = "xpath://input[@name='commit']"
SelectSearch = "xpath://input[@role='searchbox']"
Search = "xpath:(//input[@placeholder='Search'])[2]"
Folders = "xpath://span[@class='file-name-cell']//a"
FolderConfirmed = "xpath://span[text()='Folder successfully created.']"
# ResultsFolder = "xpath://a[@title='results']"
# PythonFolder = "xpath://a[text()='python']"
# ProgramsFolder = "xpath://a[@title='programs']"
# DataFolder = "xpath://a[@title='data']"
ResultsFolder = "xpath://*[text()='results']"
PythonFolder = "xpath://*[text()='python']"
ProgramsFolder = "xpath://*[text()='programs']"
DataFolder = "xpath://*[text()='data']"
DocumentsFolder = "xpath://*[text()='documents']"
