SCELogo="xpath://span[contains(text(),'CDR - SCE')]"
New="xpath://*[@class='fa fa-caret-down']"
UserOptions="xpath://a[@class='dropdown-toggle']/i[@class='fa fa-user']"
Promote="xpath://a[@title='Promote Session User Role']"
Demote="xpath://a[@title='Demote Session User Role']"
Manage="xpath://a[@title='Manage']"
ManageOrgText="xpath://h2[text()='Manage Organization']"
Organization="xpath://a[@title='Organization']"
Steps="xpath://a[@title='Steps']"
AppGroups="xpath://a[@title='App Groups']"
AppGroupRoles="xpath://a[@title='App Group Roles']"
# Upload = "id:upload"
Upload = "xpath://a[@id='upload']//i[@class='fa fa-upload']"
# Run = "id:run-file"
Run = "xpath://a[@id='run-file']//i[@class='fa fa-play']"
ConvertToCSV = "xpath://a[text()='Convert to CSV'][contains(@href,'convert')]"
Workspaces = "xpath://span[contains(text(),'Workspaces')]"
Merge = "id:workspaces-merge-link"
Pull = "id:workspaces-pull-link"
DetectDependencies = "xpath://a[@class='detect-link']"
DownloadInWorkspace = "id:download"
DownloadInStudy = "id:download-folder"
Clipboard = "xpath://a[@title='Clipboard']"
