OpenModuleChecks = "xpath://a[@title='Module Checks']"
AddNewModule = "xpath://a[text()='Add New Module']"
InputModuleName = "id:module_check_name"
InputModuleDescription = "id:module_check_description"
SelectWaiverRole = "xpath://span[contains(@id,'study_role_id-container')]"
InputWaiverRole = "xpath://input[@class='select2-search__field']"
SelectDefaultStatus = "xpath://span[contains(@id,'check_default_status-container')]"
InputDefaultStatus = "xpath://input[@class='select2-search__field']"
InputNotRun = "xpath://input[@value='Not run']"
InputFail = "xpath://input[@value='Fail']"
InputPass = "xpath://input[@value='Pass']"
InputCheckManually = "xpath://input[@value='Check manually']"
RadioManual = "id:module_check_automatic_false"
RadioAutomatic = "id:module_check_automatic_true"
RadioPreventPromotionTrue = "id:module_check_prevents_promotion_true"
RadioPreventPromotionFalse = "id:module_check_prevents_promotion_false"
RadioResetRerunTrue = "id:module_check_rerun_true"
RadioResetRerunFalse = "id:module_check_rerun_false"
CreateButton = "xpath://button[text()='Create']"
CancelButton = "xpath://button[text()='Cancel']"
ModuleCreatedPrompt = "xpath://span[text()='Module created successfully.']"
NewModuleCell = "xpath://span[contains(text(),'xyz')]"
