NewStudy = "xpath://a[contains(@title,'Create a new study')]"
LibProjButton = "id:select2-study_parent_id-container"
LibProjSelect = "xpath:(//select[contains(@class,'select_storage')])[1]"
# FirstLibrary = "xpath://li[@id='select2-study_parent_id-result-uloe-7558']//i[@class='fa fa-briefcase']"
TemplateButton = "id:select2-template_id-container"
StudySearch = "xpath://input[@role='searchbox']"
TemplateSelect = "xpath:(//select[contains(@class,'select_storage')])[2]"
StudyNumber = "id:study_study_number"
StudyName = "id:study_name"
StudyTitle = "id:study_title"
IsTemplate = "id:study_is_template"
StorageButton = "id:select2-study_storage_id-container"
StorageSelect = "id:study_storage_id"
CreateStudy = "xpath://input[@name='commit']"
StudyConfirmed = "xpath://span[text()='Study was successfully created.']"
StudyRequest = "xpath://span[contains(text(),'Your study creation request has been initiated.')]"
