OpenWorkflows = "xpath://a[@title='Workflows']"
AddNewWorkflow = "xpath://a[text()='Add New Workflow']"
InputWorkflowName = "id:workflow_name"
InputWorkflowDescription = "id:workflow_description"
InputWorkflowDuration = "id:workflow_duration"
AddAnotherStep = "xpath://a[@class='add_nested_fields']"
SelectStep = "xpath://span[@class='select2-selection__arrow']"
InputStepName = "xpath://input[@role='searchbox']"
CreateButton = "xpath://button[text()='Create']"
CancelButton = "xpath://button[text()='Cancel']"
WorkflowCreatedPrompt = "xpath://span[text()='Workflow created successfully.']"
NewWorkflowCell = "xpath://span[contains(text(),'xyz')]"
