OpenGlobalRoles = "xpath://a[@title='Global Roles']"
AddNewGlobalRole = "xpath://button[text()='Add New Global Role']"
GlobalRoleCreatedPrompt = "xpath://span[contains(text(),'Global Role')][contains(text(),'successfully created')]"
UnblindedPerm = "xpath:(//div[contains(@data-testid,'unblinded')])[1]"
ExecutePerm = "xpath:(//div[contains(@data-testid,'can_execute')])[1]"
ManageAccessPerm = "xpath:(//div[contains(@data-testid,'can_manage')])[1]"
ManageTasksPerm = "xpath:(//div[contains(@data-testid,'can_manage_task')])[1]"
ChangeRolePerm = "xpath:(//div[contains(@data-testid,'can_change_role')])[1]"
CanExportPerm = "xpath:(//div[contains(@data-testid,'can_export')])[1]"
SaveGlobalRoleChanges = "xpath://button[@title='Save']"
GlobalRoleChangesSavedPrompt = "xpath://span[text()='Successfully updated 1 Global Role(s).']"
GlobalRoleActionMenu = "xpath:(//i[@data-testid='study-role-action-menu'])[1]"
RenameGlobalRoleOption = "xpath://div[text()='Rename Role']"
# GlobalRoleNameInput = "xpath://span[@class='study-role-name']//input[@type='text']"
GlobalRoleNameInput = "xpath://input"
FirstGlobalRoleName = "xpath:(//span[@class='study-role-name']//span)[1]"
GlobalRoleNameUpdatedPrompt = "xpath://span[contains(text(),'Global Role')][contains(text(),'successfully updated')]"
GlobalRoleFilterMenu = "xpath://i[@class='fa fa-filter']"
GlobalRoleFilterNameSelect = "xpath:(//div[contains(@class,'filter-select__control')])[1]"
GlobalRoleFilterNameInput = "xpath:(//input[contains(@id,'react-select')])[1]"
GlobalRoleFilterNameClear = "xpath://div[contains(@class,'filter-select__clear-indicator')]"
GlobalRoleFilterApply = "xpath://button[text()='Apply']"
GlobalRoleFilterClear = "xpath://button[text()='Clear']"
